output "public_ip_address" {
  description = "Public IP address of the public VM"
  value       = module.vm.public_ip_address
}

output "public_vm_private_ip" {
  description = "Private IP address of the public VM"
  value       = module.vm.public_vm_private_ip
}

output "private_vm_private_ip" {
  description = "Private IP address of the private VM"
  value       = module.vm.private_vm_private_ip
}


output "ssh_private_key_pem" {
  description = "SSH private key generated by the SSH module"
  value       = module.ssh_key.private_key_pem
  sensitive   = true
}